server:
  port: 8088


user-servive:
  ribbon:
    listOfServers: localhost:8082, localhost:8083

todo-servive:
  ribbon:
    listOfServers: localhost:8081

zuul:
  routes:
    user:
#      url: http://localhost:8082/users
      path: /api/users/**
      serviceId: user-servive
      sensitiveHeaders:

    todo:
      path: /api/todos/**
      serviceId: todo-servive
      sensitiveHeaders: